import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    ".wrangler/**", // Generated local Worker bundles and persistence fixtures.
    "public/vendor/contracts/**", // Unmodified pinned upstream distributions, verified by hash.
    "public/pdf-assets/**", // Unmodified generated Mozilla distribution.
    "next-env.d.ts",
    "worker-configuration.d.ts", // Generated by Wrangler, not application source.
  ]),
]);

export default eslintConfig;
