import{test}from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import ts from'typescript';
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n],AbortSignal,TextDecoder});return exports;}
const history=load('lib/crm/assessment-history.ts'),repository=load('lib/documents/repository.ts');const submissionId='00000000-0000-0000-0000-000000000001',iin='000000000001',card='SYNTHETIC LAWYER CARD';
function fixture({lost=false,reject=false,wrongIdentity=false,comments=[]}={}){let writes=0;const send=async(url,init)=>{const body=JSON.parse(init.body);if(url.endsWith('crm.deal.get.json'))return Response.json({result:{ID:'11665',UF_CRM_AI_IIN:wrongIdentity?'other':iin}});if(url.endsWith('crm.timeline.comment.list.json')){assert.equal(body.filter.ENTITY_ID,11665);assert.equal(body.filter.ENTITY_TYPE,'deal');const next=body.start+50;return Response.json({result:comments.slice(body.start,next),...(comments.length>next?{next}:{})});}assert.ok(url.endsWith('crm.timeline.comment.add.json'));writes++;assert.equal(body.fields.ENTITY_TYPE,'deal');assert.equal(body.fields.ENTITY_ID,11665);if(!reject)comments.push({ID:String(comments.length+1),ENTITY_ID:'11665',ENTITY_TYPE:'deal',COMMENT:body.fields.COMMENT});if(lost)throw Error('lost response');return Response.json({result:comments.length});};return{adapter:history.createAssessmentHistoryAdapter('https://synthetic.invalid/',send),writes:()=>writes,comments};}
test('history writes the lawyer snapshot once and verifies a lost add response',async()=>{const f=fixture({lost:true});const a=await f.adapter.append('11665',iin,submissionId,card);assert.equal(a.verified,true);assert.match(f.comments[0].COMMENT,/SYNTHETIC LAWYER CARD/);assert.equal((await f.adapter.append('11665',iin,submissionId,card)).commentId,a.commentId);assert.equal(f.writes(),1);});
test('history reconciliation is read-only and mismatched reference content is not accepted',async()=>{const f=fixture();assert.equal(await f.adapter.reconcile('11665',iin,submissionId,card),null);assert.equal(f.writes(),0);await f.adapter.append('11665',iin,submissionId,card);f.comments[0].COMMENT='CHANGED\n\nAssessment reference: '+submissionId;await assert.rejects(f.adapter.append('11665',iin,submissionId,card),/HISTORY_CONTENT_MISMATCH/);assert.equal(f.writes(),1);});
test('history pagination finds an earlier snapshot and refuses duplicate references',async()=>{const comments=Array.from({length:51},(_,i)=>({ID:String(i+1),ENTITY_ID:'11665',ENTITY_TYPE:'deal',COMMENT:'OTHER'}));comments[50].COMMENT=card+'\n\nAssessment reference: '+submissionId;const f=fixture({comments});assert.equal((await f.adapter.append('11665',iin,submissionId,card)).commentId,'51');assert.equal(f.writes(),0);comments[0].COMMENT=comments[50].COMMENT;await assert.rejects(f.adapter.reconcile('11665',iin,submissionId,card),/HISTORY_DUPLICATE_REFERENCE/);});
test('wrong client or unconfirmed creation cannot report success',async()=>{const wrong=fixture({wrongIdentity:true});await assert.rejects(wrong.adapter.append('11665',iin,submissionId,card),/CASE_IDENTITY_CHANGED/);assert.equal(wrong.writes(),0);const rejected=fixture({reject:true});await assert.rejects(rejected.adapter.append('11665',iin,submissionId,card),/HISTORY_OUTCOME_UNCERTAIN/);assert.equal(rejected.writes(),1);assert.equal(await rejected.adapter.reconcile('11665',iin,submissionId,card),null);assert.equal(rejected.writes(),1);});
test('history service never reposts a writing or uncertain history intent',async()=>{
 const service=load('lib/questionnaire/submission-history.ts',{'../documents/repository':repository,'../crm/assessment-history':history});let adds=0,reads=0;
 const row={id:submissionId,state:'verified',history_state:'pending',identity_revision:1,actor_id:'worker',payload_json:JSON.stringify({lawyerCard:card})};
 const repo={get:async()=>row,claimHistory:async()=>{row.history_state='writing';return true;},finishHistory:async(c,id,commentId)=>{row.history_state=commentId?'verified':'uncertain';return row;}};
 const adapter={append:async()=>{adds++;throw new history.AssessmentHistoryError('HISTORY_OUTCOME_UNCERTAIN');},reconcile:async()=>{reads++;return null;}};
 const args=[repo,adapter,{id:'case',external_id:'11665',client_iin:iin,identity_revision:1},{id:'worker'},'request'];await service.saveSubmissionHistory(...args);assert.equal(row.history_state,'uncertain');await service.saveSubmissionHistory(...args);assert.equal(adds,1);assert.equal(reads,1);adapter.reconcile=async()=>({commentId:'5',verified:true});await service.saveSubmissionHistory(...args);assert.equal(row.history_state,'verified');await service.saveSubmissionHistory(...args);assert.equal(adds,1);
});
