import test from 'node:test';import assert from 'node:assert/strict';import{session,TEST_SECRET,testCookie}from'./session-helper.mjs';import{readFile}from'node:fs/promises';import ts from'typescript';import vm from'node:vm';
const {default:worker}=await import('../dist/server/index.js');
const env={SITE_SESSION_TOKEN:TEST_SECRET,ASSETS:{fetch:async()=>new Response('not found',{status:404})}},ctx={waitUntil(){},passThroughOnException(){}};
test('anonymous visitors cannot read page, static form or CRM APIs',async()=>{for(const path of ['/','/assessment-card','/assessment-card.html','/api/sales-metrics','/api/bitrix/crm.deal.get','/api/status']){const r=await worker.fetch(new Request('https://site.test'+path),env,ctx);assert.equal(r.status,path.startsWith('/api/')?401:303,path)}});
test('all four worker sessions are signed, expiring and resistant to identity changes',async()=>{for(const id of ['ali','ramazan','nurdaulet','darkhan']){const token=await session.issueSession(id,TEST_SECRET,1000);assert.equal((await session.verifySession(token,TEST_SECRET,1001)).worker,id);assert.equal(await session.verifySession(token,TEST_SECRET,1000+session.SESSION_SECONDS),null);assert.equal(await session.verifySession(token+'x',TEST_SECRET,1001),null)}});
test('authenticated form is private and payment shortcut is present',async()=>{const r=await worker.fetch(new Request('https://site.test/assessment-card',{headers:{cookie:await testCookie()}}),env,ctx);assert.equal(r.status,200);assert.match(r.headers.get('cache-control'),/no-store/);const html=await r.text();assert.match(html,/Контроль оплат/);assert.match(html,/id="signOut"/)});
test('forged identities and cross-origin CRM mutations are denied',async()=>{const forged=await worker.fetch(new Request('https://site.test/api/sales-metrics',{headers:{cookie:'__Host-antikrizis_assessment_session=ali.fake','oai-authenticated-user-email':'ali@example.test'}}),env,ctx);assert.equal(forged.status,401);const r=await worker.fetch(new Request('https://site.test/api/bitrix/crm.deal.update',{method:'POST',headers:{cookie:await testCookie(),origin:'https://evil.test'}}),env,ctx);assert.equal(r.status,403)});
const routeSource=await readFile(new URL('../app/api/session/route.ts',import.meta.url),'utf8');
function loginRoute(fetch){const context=vm.createContext({exports:{},require:()=>session,process:{env:{SITE_SESSION_TOKEN:TEST_SECRET}},fetch,Request,Response,URL,AbortSignal,TextDecoder,Uint8Array});vm.runInContext(ts.transpileModule(routeSource,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);return context.exports}
const request=(origin='https://site.test')=>new Request('https://site.test/api/session',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({worker:'ramazan',password:'synthetic-only'})});
test('login reuses existing payment authentication and creates a site-specific cookie',async()=>{let calls=0;const route=loginRoute(async(url,options)=>{calls++;assert.equal(url,'https://antikrizis-payment-control.mukhamet-ali-ma.chatgpt.site/api/session');assert.equal(JSON.parse(options.body).worker,'ramazan');return Response.json({ok:true,data:{displayName:'Ramazan'}},{headers:{'set-cookie':'antikrizis_payment_session=synthetic; Secure; HttpOnly'}})});const r=await route.POST(request());assert.equal(r.status,200);assert.equal(calls,1);const cookie=r.headers.get('set-cookie');assert.match(cookie,/__Host-antikrizis_assessment_session=/);assert.match(cookie,/HttpOnly; Secure; SameSite=Strict/);const token=session.readSessionCookie(cookie);assert.equal((await session.verifySession(token,TEST_SECRET)).worker,'ramazan');const logout=await route.DELETE(new Request('https://site.test/api/session',{method:'DELETE',headers:{origin:'https://site.test'}}));assert.match(logout.headers.get('set-cookie'),/Max-Age=0/)});
test('invalid password, login service failure and cross-origin login create no session',async()=>{for(const fetch of [async()=>Response.json({error:'bad'},{status:401}),async()=>{throw Error('down')}]){const r=await loginRoute(fetch).POST(request());assert.ok([401,503].includes(r.status));assert.equal(r.headers.get('set-cookie'),null)}const r=await loginRoute(()=>{throw Error('must not call')}).POST(request('https://evil.test'));assert.equal(r.status,403)});
