import {test}from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import ts from'typescript';
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n],Date,Map,Set,BigInt});return exports;}
const policy=load('lib/documents/policy.ts'),{matchShortReport}=load('lib/documents/credit-report-match.ts',{'./policy':policy,'./loan-identity':load('lib/documents/loan-identity.ts')});
const credit=(number,debt='100.25',page=1)=>({contractNumber:number,page,facts:[{key:'creditor',value:'ТЕСТ БАНК'},{key:'debtOutstanding',value:debt},{key:'overdueDays',value:'0'}],components:{}});
function fixture(){const report=(kind,credits,findings=[])=>({read:{pages:[{page:1,needsOcr:false}]},extraction:{kind,identity:{iin:'test-client'},issuedAt:'2026-09-10',credits,findings}});return {short:report('gkb_short',[credit('ABC123..')],['SHORT_CONTRACT_ID_TRUNCATED','SHORT_CREDIT_LIST_UNVERIFIED']),full:report('gkb_full',[credit('ABC123456','100.25',3)])};}
const run=s=>matchShortReport(s.short,s.full,'test-client','2026-09-10');
test('unique same-client same-day complete reports link source pages without rewriting evidence',()=>{const s=fixture(),before=JSON.stringify(s);const r=run(s);assert.equal(r.length,1);assert.equal(r[0].fullNumber,'ABC123456');assert.equal(r[0].shortPage,1);assert.equal(r[0].fullPage,3);assert.equal(JSON.stringify(s),before);});
test('ambiguous prefix matching is rejected even if array order could pick a loan',()=>{const s=fixture();s.short.extraction.credits.push(credit('ABC123..'));s.full.extraction.credits.push(credit('ABC123789'));assert.equal(run(s),null);});
test('cannot consume the same full loan twice',()=>{const s=fixture();s.short.extraction.credits.push(credit('ABC123..'));s.full.extraction.credits.push(credit('OTHER123'));assert.equal(run(s),null);});
test('wrong identity, stale/different dates, OCR, incomplete totals, duplicate rows and ambiguous debt stay blocked',()=>{
 for(const change of [s=>s.full.extraction.identity.iin='other',s=>s.short.extraction.identity.iin=null,s=>s.full.extraction.issuedAt='2026-09-09',s=>{s.full.extraction.issuedAt=s.short.extraction.issuedAt='2026-08-01';},s=>s.full.read.pages[0].needsOcr=true,s=>s.short.read.pages=[],s=>s.short.extraction.findings.push('SHORT_TOTAL_MISMATCH'),s=>s.short.extraction.findings.push('SHORT_DUPLICATE_CREDIT'),s=>s.full.extraction.findings.push('TOTAL_DEBT_REQUIRES_RECONCILIATION'),s=>s.full.extraction.credits[0].facts.pop(),s=>s.full.extraction.credits[0].facts[1].value='100.26',s=>s.full.extraction.credits[0].facts[0].value='OTHER BANK',s=>s.full.extraction.credits.push(credit('OTHER'))]){const s=fixture();change(s);assert.equal(run(s),null);}
});
test('contract masks are literal, require visible identity, and cannot match an already shortened full ID',()=>{
 for(const [short,full,ok]of [['ABC123…','ABC123XYZ',true],['ABC123..ZZ','ABC123456ZZ',true],['ABC123..ZZ','ABC123456XX',false],['ABC123..','ABC123',false],['ABC..','ABC999',false],['ABC123..','ABC123..',false],['ABC(12)..','ABC(12)XYZ',true],['ABC(12)..','ABC12XYZ',false]]){const s=fixture();s.short.extraction.credits[0].contractNumber=short;s.full.extraction.credits[0].contractNumber=full;assert.equal(run(s)!==null,ok,short+' / '+full);}
});
test('staff warning distinguishes different loan counts and unresolved full-report debt',()=>{
 const {shortReportMismatchReasons}=load('lib/documents/credit-report-match.ts',{'./policy':policy,'./loan-identity':load('lib/documents/loan-identity.ts')});const s=fixture();s.full.extraction.credits.push(credit('SECOND'));s.full.extraction.findings.push('TOTAL_DEBT_REQUIRES_RECONCILIATION');const reasons=shortReportMismatchReasons(s.short,s.full,'2026-09-10').join(' ');assert.match(reasons,/краткий ГКБ — 1, полный — 2/);assert.match(reasons,/остаток, просрочку/);assert.match(reasons,/без задолженности и просрочки/);assert.match(reasons,/Не исключайте договор без проверки/);assert.equal(run(s),null);
});
test('legal-form spelling and whitespace around an omission link the exact same loan',()=>{
 const s=fixture();s.short.extraction.credits[0].contractNumber='ABC123 ..';s.short.extraction.credits[0].facts[0].value='Акционерное общество «Example Bank»';s.full.extraction.credits[0].facts[0].value='АО "Example Bank"';assert.equal(run(s)?.length,1);
 for(const name of ['АО "Other Bank"','ТОО "Example Bank"','АО "Example Bank" (ДБ Other Bank)']){s.full.extraction.credits[0].facts[0].value=name;assert.equal(run(s),null,name);}
});
test('unused active limits can be absent from the short report only with explicit zero debt and overdue',()=>{
 const s=fixture();s.full.extraction.credits.push(credit('ZERO-LIMIT','0.00'));assert.equal(run(s)?.length,1);
 for(const change of [c=>c.facts[1].value='0.01',c=>c.facts[1].value='',c=>c.facts[2].value='1',c=>c.facts.pop()]){const r=fixture();const extra=credit('ZERO-LIMIT','0.00');change(extra);r.full.extraction.credits.push(extra);assert.equal(run(r),null);}
});
