import{test}from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import ts from'typescript';import{createHash}from'node:crypto';
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>imports[n],URL,Map,Set,Uint8Array,AbortSignal,btoa,TextEncoder,ReadableStream,fetch:()=>{throw Error('Unexpected network request')}});return exports;}
const upload=load('lib/crm/document-upload.ts',{'../documents/repository':{sha256:async b=>createHash('sha256').update(b).digest('hex')}}),{createCrmDocumentReader,createVerifiedDocumentUploadAdapter}=load('lib/crm/document-download.ts',{'./document-upload':upload});
const portal='https://crm.example',webhook=portal+'/rest/1/test/',iin='000000000010';
function metadata(patch={}){return Response.json({result:{item:{id:11665,ufCrmAiIin:iin,ufCrmAnkPrimaryDocs:[{id:22,urlMachine:portal+'/rest/crm.controller.item.getFile.json?token=synthetic'}],...patch}}});}
test('download refreshes machine link from exact deal and emits only bytes',async()=>{const calls=[];const read=createCrmDocumentReader(webhook,'11665',iin,async(url,options)=>{calls.push({url,options});return options.method==='POST'?metadata():new Response(new Uint8Array([1,2,3]));});assert.deepEqual(await read({id:'22'}),new Uint8Array([1,2,3]));assert.deepEqual(await read({id:'22'}),new Uint8Array([1,2,3]));assert.equal(calls.filter(c=>c.options.method==='POST').length,2);assert.equal(JSON.parse(calls[0].options.body).id,'11665');assert.equal(calls[1].options.credentials,'omit');assert.equal(calls[1].options.redirect,'manual');});
test('wrong client, foreign file and untrusted link stop before download',async()=>{for(const patch of [{ufCrmAiIin:'other'},{ufCrmAnkPrimaryDocs:[]},{ufCrmAnkPrimaryDocs:[{id:22,urlMachine:'https://other.example/file'}]}]){let downloads=0;const read=createCrmDocumentReader(webhook,'11665',iin,async(url,o)=>{if(o.method==='POST')return metadata(patch);downloads++;return new Response('x');});await assert.rejects(read({id:'22'}));assert.equal(downloads,0);}});
test('same-origin storage redirect works; cross-origin never receives a request',async()=>{for(const foreign of [false,true]){const calls=[];const read=createCrmDocumentReader(webhook,'11665',iin,async(url,o)=>{calls.push(url);if(o.method==='POST')return metadata();if(url.includes('getFile'))return new Response(null,{status:302,headers:{location:foreign?'https://unverified-storage.example/file':'/upload/file'}});return new Response('verified test bytes');});if(foreign){await assert.rejects(read({id:'22'}),/REDIRECT_UNTRUSTED/);assert.equal(calls.length,2);}else assert.equal(new TextDecoder().decode(await read({id:'22'})),'verified test bytes');}});
test('oversize or expired downloads fail without leaking token-bearing errors',async()=>{for(const response of [()=>new Response('x',{headers:{'content-length':String(36*1024*1024)}}),()=>new Response(null,{status:401})]){const read=createCrmDocumentReader(webhook,'11665',iin,async(url,o)=>o.method==='POST'?metadata():response());await assert.rejects(read({id:'22'}),e=>e instanceof upload.DocumentUploadError&&!e.message.includes('token'));}});
test('verified upload factory uses CRM byte download for content readback',async()=>{let uploaded=false;const adapter=createVerifiedDocumentUploadAdapter(webhook,'11665',iin,async(url,o)=>{if(url.includes('crm.item.update')){const body=await new Response(o.body).json();assert.equal(body.fields.ufCrmAnkPrimaryDocs[0][1],'AQID');uploaded=true;return metadata();}if(url.includes('crm.item.get'))return uploaded?metadata():metadata({ufCrmAnkPrimaryDocs:[]});return new Response(new Uint8Array([1,2,3]));});const r=await adapter.append('11665',iin,[],[{name:'SYNTHETIC.pdf',bytes:new Uint8Array([1,2,3])}]);assert.equal(r.verified,true);assert.equal(r.files[0].id,'22');});

test('malformed download configuration exposes only a fixed error code',()=>{assert.throws(()=>createCrmDocumentReader('not-a-url-containing-synthetic-secret','11665',iin),e=>e.code==='INVALID_DOWNLOAD_CONFIGURATION'&&!e.message.includes('synthetic-secret'));});


test('PDF import preserves safe names but excludes signing keys before reading their body',async()=>{
 const names=[];let cancelled=false;
 const stream=new ReadableStream({cancel(){cancelled=true;}});
 const reader=createCrmDocumentReader(webhook,'11665',iin,async(url,o)=>o.method==='POST'?metadata():new Response(stream,{headers:{'content-disposition':'attachment; filename="SYNTHETIC_SECRET.pfx"'}}),{pdfOnly:true,onFilename:n=>names.push(n)});
 await assert.rejects(reader({id:'22'}),/CREDENTIAL_NOT_ANALYSED/);assert.equal(cancelled,true);assert.equal(names.length,0);
 const pdf=createCrmDocumentReader(webhook,'11665',iin,async(url,o)=>o.method==='POST'?metadata():new Response('%PDF-1.7',{headers:{'content-disposition':"attachment; filename*=UTF-8''%D0%A2%D0%B5%D1%81%D1%82.pdf"}}),{pdfOnly:true,onFilename:n=>names.push(n)});
 assert.equal(new TextDecoder().decode(await pdf({id:'22'})),'%PDF-1.7');assert.deepEqual(names,['Тест.pdf']);
});
