import{test}from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import ts from'typescript';
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:n=>n==='../../public/contract-words.mjs'?{CONTRACT_RENDERER_VERSION:'a'.repeat(64)}:imports[n]});return exports;}
const repository=load('lib/documents/repository.ts');
function setup(){let ready=true,writes=0,reads=0,reviewIds=['doc-review'],row=null;
 const record={id:'case',external_id:'11665',client_iin:'synthetic',identity_revision:1},actor={id:'worker:synthetic'},draft={answers:['test'],documents:[]},values={iin:'synthetic',card:'TEST'};
 const submissions={get:async()=>row,prepare:async(r,id,p,a)=>row={request_id:id,identity_revision:r.identity_revision,actor_id:a.id,state:'prepared',payload_json:JSON.stringify(p)}};
 const adapter={read:async()=>{reads++;return{iin:'synthetic'};}};
 const service=load('lib/questionnaire/final-submission.ts',{'../documents/repository':repository,'./history-snapshot':load('lib/questionnaire/history-snapshot.ts'),'./draft':{validateDraft:v=>v},'./review-bindings':{parseReviewBindings:v=>v||[]},'./final-check':{FINAL_VALIDATION_VERSION:'test-v',finalCheck:async()=>({payload:draft,compiled:{values},reviewIds,publicResult:{readyToSubmit:ready,preview:{contractData:{contract_number:'TEST'}},evidence:{approved:[]}}})},'./submission-service':{submitValidatedAssessment:async()=>{writes++;return row={...row,state:'verified'};}}});
 const args=[{},submissions,adapter,record,actor,'request'];return{prepare:()=>service.prepareFinalSubmission(...args,1,draft,[],'2026-09-10'),commit:()=>service.commitFinalSubmission(...args,'2026-09-10'),ready:v=>ready=v,reviews:v=>reviewIds=v,counts:()=>({writes,reads}),row:()=>row,actor,draft};
}
test('server preparation writes no CRM fields, and a repeated commit does not resend',async()=>{const s=setup();await s.prepare();assert.equal(s.counts().writes,0);await s.prepare();assert.equal(s.counts().reads,1);await s.commit();await s.commit();assert.equal(s.counts().writes,1);});
test('incomplete package cannot prepare, or commit after its approval is withdrawn',async()=>{const s=setup();s.ready(false);await assert.rejects(s.prepare(),/ASSESSMENT_NOT_READY/);assert.equal(s.counts().reads,0);s.ready(true);await s.prepare();s.ready(false);await assert.rejects(s.commit(),/ASSESSMENT_NOT_READY/);assert.equal(s.counts().writes,0);});
test('changed review identity, actor and reused request with different answers are rejected',async()=>{const s=setup();await s.prepare();s.reviews(['new-review']);await assert.rejects(s.commit(),/SUBMISSION_EVIDENCE_CHANGED/);s.actor.id='other';await assert.rejects(s.commit(),/SUBMISSION_ACTOR_OR_IDENTITY_CHANGED/);s.actor.id='worker:synthetic';s.draft.answers=['changed'];await assert.rejects(s.prepare(),/IDEMPOTENCY_KEY_REUSED/);assert.equal(s.counts().writes,0);});
test('uncertain submission reconciliation uses its immutable saved values and never submits again',async()=>{
 let finishes=0,reads=0;const values={iin:'synthetic',card:'ORIGINAL SAVED CARD'};const row={state:'uncertain',actor_id:'worker',identity_revision:1,payload_json:JSON.stringify({values})};const submissions={get:async()=>row,finish:async(c,id,verified,code)=>{finishes++;assert.equal(verified,true);assert.equal(code,'READBACK_RECONCILED');return{...row,state:'verified'};}};
 const service=load('lib/questionnaire/final-submission.ts',{'../documents/repository':repository});const adapter={reconcile:async(id,iin,snapshot)=>{reads++;assert.equal(snapshot.card,values.card);return{verified:true,mismatches:[]};},save:async()=>assert.fail('Reconciliation must not write')};
 const result=await service.reconcileFinalSubmission(submissions,adapter,{id:'case',external_id:'11665',client_iin:'synthetic',identity_revision:1},{id:'worker'},'request');assert.equal(result.state,'verified');assert.equal(finishes,1);assert.equal(reads,1);
 row.state='prepared';await service.reconcileFinalSubmission(submissions,adapter,{id:'case',external_id:'11665',client_iin:'synthetic',identity_revision:1},{id:'worker'},'request');assert.equal(reads,1);
});
test('mismatched or unavailable readback cannot report a recovered save',async()=>{
 const row={state:'uncertain',actor_id:'worker',identity_revision:1,payload_json:JSON.stringify({values:{iin:'synthetic'}})};let finishes=0;const submissions={get:async()=>row,finish:async(c,id,verified,code)=>{finishes++;assert.equal(verified,false);assert.equal(code,'ASSESSMENT_READBACK_MISMATCH');return row;}};
 const service=load('lib/questionnaire/final-submission.ts',{'../documents/repository':repository});const args=[submissions,null,{id:'case',external_id:'11665',client_iin:'synthetic',identity_revision:1},{id:'worker'},'request'];args[1]={reconcile:async()=>({verified:false,mismatches:['card']})};assert.equal((await service.reconcileFinalSubmission(...args)).state,'uncertain');assert.equal(finishes,1);
 args[1]={reconcile:async()=>{throw Error('Synthetic read unavailable');}};await assert.rejects(service.reconcileFinalSubmission(...args),/Synthetic read unavailable/);assert.equal(finishes,1);
});
test('final contract download uses saved data and renderer only after both receipts verify',async()=>{
 const row={state:'verified',history_state:'uncertain',identity_revision:1,actor_id:'worker',payload_json:JSON.stringify({contractData:{client_name:'SAVED PERSON'},contractRendererVersion:'b'.repeat(64)})};
 const service=load('lib/questionnaire/final-submission.ts',{'../documents/repository':repository}),args=[{get:async()=>row},{id:'case',identity_revision:1},{id:'worker'},'request'];await assert.rejects(service.savedContract(...args),/SUBMISSION_NOT_FINISHED/);row.history_state='verified';const result=await service.savedContract(...args);assert.equal(result.data.client_name,'SAVED PERSON');assert.equal(result.rendererVersion,'b'.repeat(64));
});
