import {JSDOM} from 'jsdom';import {indexedDB} from 'fake-indexeddb';import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
const root='public/';const html=fs.readFileSync(root+'questionnaire.html','utf8');const iin='991231300003'; // synthetic fixture identifier only
const ctx={client:{external:{system:'bitrix',dealId:'11665'},title:'SYNTHETIC ONLY',iin},caseId:'test-case',identityRevision:1,assessmentDay:'2026-09-10'};
const payload={...ctx,documentId:'test-document',extractionId:'test-extraction',persisted:true,eligibleForAutofill:true,findings:[],document:{totalPages:1,pdfSha256:'test-hash',pages:[{page:1,text:'SYNTHETIC ONLY'}],extraction:{kind:'gkb_full',identity:{iin,name:'SYNTHETIC CLIENT'},issuedAt:'2026-09-10',facts:[{key:'identity.iin',value:iin,page:1,source:'IIN'},{key:'identity.name',value:'SYNTHETIC CLIENT',page:1,source:'Name'}],credits:[{contractNumber:'TEST-001',page:1,facts:[{key:'creditor',value:'SYNTHETIC BANK',page:1,source:'Creditor'},{key:'monthlyPayment',value:'20.00',page:1,source:'Payment'}]}]}}};
function setup(blocked=false,replayed=false){const dom=new JSDOM(html,{url:'http://127.0.0.1:4193/questionnaire.html',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.indexedDB=indexedDB;w.structuredClone=structuredClone;w.crypto.randomUUID=()=>webcrypto.randomUUID();w.HTMLElement.prototype.getClientRects=function(){return this.isConnected&&!this.closest('.hidden')?[{}]:[]};w.HTMLElement.prototype.scrollIntoView=function(){};w.URL.createObjectURL=()=>'';w.URL.revokeObjectURL=()=>{};w.prompt=()=> 'Synthetic correction reason';let fail=false;const reviews=[];
 w.fetch=async(url,opts={})=>{if(url==='/api/assessment/11665')return{ok:true,json:async()=>structuredClone(ctx)};if(url==='/api/assessment/11665/documents')return{ok:true,json:async()=>({...structuredClone(payload),eligibleForAutofill:!blocked,findings:blocked?['GKB_TOO_OLD']:[],reviews:replayed?[{id:'prior-review',fact_key:'credits.0.monthlyPayment',value_json:'"25.00"',disposition:'corrected',reason:'prior correction'}]:[]})};if(url==='/api/assessment/11665/reviews'){reviews.push(JSON.parse(opts.body));return{ok:!fail,json:async()=>fail?{error:'GKB_DATE_NOT_ACCEPTABLE'}:{ok:true,review:{id:'stored-'+reviews.at(-1).requestId}}};}throw Error('Unexpected URL '+url);};
 const v=dom.getInternalVMContext(),run=s=>vm.runInContext(s,v);for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))run(match[1]);run(fs.readFileSync(root+'loan-status.js','utf8'));run(fs.readFileSync(root+'money-input.js','utf8'));run(fs.readFileSync(root+'hosted-assessment.js','utf8'));run(fs.readFileSync(root+'assessment-review.js','utf8'));
 return{dom,w,run,reviews,setFail:v=>fail=v,async load(){w.document.getElementById('hostDealId').value='11665';await w.document.getElementById('hostLoadDeal').onclick();const input=w.document.getElementById('previewDocuments');Object.defineProperty(input,'files',{value:[new w.File(['synthetic'],'test.pdf',{type:'application/pdf'})],configurable:true});input.dispatchEvent(new w.Event('change',{bubbles:true}));await w.document.getElementById('afAnalyze').onclick();}};
}
(async()=>{const p=setup();await p.load();const d=p.w.document;assert.equal(d.getElementById('fio').value,'SYNTHETIC CLIENT');const payment=d.querySelector('#creditors input[id^="n8041"]');assert.equal(payment.value,'20.00');assert.ok(p.run('af.sources.get("'+payment.id+'").serverFactKey')==='credits.0.monthlyPayment');
 p.setFail(true);let button=payment.closest('.field').querySelector('.af-source button:last-child');await button.onclick();assert.ok(p.run('af.sources.get("'+payment.id+'").pending'));const requestId=p.reviews[0].requestId;p.setFail(false);await button.onclick();assert.equal(p.reviews[1].requestId,requestId);assert.equal(p.run('af.sources.get("'+payment.id+'").pending'),false);assert.equal(p.reviews[1].value,'20.00');
 payment.value='25.00';payment.dispatchEvent(new p.w.Event('input',{bubbles:true}));assert.ok(p.run('af.sources.get("'+payment.id+'").pending'));const reason=payment.closest('.field').querySelector('.af-source textarea');reason.value='Synthetic correction reason';reason.dispatchEvent(new p.w.Event('input',{bubbles:true}));button=payment.closest('.field').querySelector('.af-source button:last-child');await button.onclick();assert.equal(p.reviews[2].disposition,'corrected');assert.equal(p.reviews[2].reason,'Synthetic correction reason');assert.notEqual(p.reviews[2].requestId,requestId);
 d.getElementById('hostDealId').value='11666';await d.getElementById('hostLoadDeal').onclick();assert.equal(p.w.HostedAssessment.getContext().client.external.dealId,'11665');assert.equal(d.getElementById('fio').value,'SYNTHETIC CLIENT');assert.match(d.getElementById('afStatus').textContent,/Сохраните черновик/);
 const blocked=setup(true);await blocked.load();assert.equal(blocked.w.document.getElementById('fio').value,'');assert.equal(blocked.run('af.sources.size'),0);assert.ok(blocked.run('missingDocuments().includes("ГКБ — полный отчёт")'));
 const replay=setup(false,true);await replay.load();const rp=replay.w.document.querySelector('#creditors input[id^=n8041]');assert.equal(rp.value,'25.00');assert.equal(replay.run('af.sources.get("'+rp.id+'").pending'),false);assert.equal(replay.run('af.sources.get("'+rp.id+'").value'),'20.00');
 assert.equal(replay.run('[...af.results.values()][0].creditEvidence.credits[0].facts.find(f=>f.key==="monthlyPayment").value'),'20.00','report comparison must retain original evidence despite a saved correction');
 console.log('PASS: hosted autofill, server fact keys, rejected review stays pending, retry key reused, correction reason persisted, case switch blocked, stale GKB not filled');await new Promise(r=>setTimeout(r,100));p.dom.window.close();blocked.dom.window.close();replay.dom.window.close();})().catch(e=>{console.error(e);process.exit(1)});
