import{test}from'node:test';import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import ts from'typescript';
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(new URL('../'+file,import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true}}).outputText,{exports,require:n=>imports[n],Date,Map,Set});return exports;}
const {extractPowerParties}=load('lib/documents/power-of-attorney.ts'),policy=load('lib/documents/policy.ts');
const approved=[{kind:'person',legalName:'TEST APPROVED PERSON',identifier:'000000000002'},{kind:'organization',legalName:'ТОО «TEST ORGANIZATION»',identifier:'000000000003'}];
const {checkPowerRepresentative}=load('lib/documents/power-validation.ts',{'./policy':policy,'./approved-representatives.server.json':approved});
const power='НОТАРИУС ИИН 000000000099\nДОВЕРЕННОСТЬ\nЯ, гр. TEST PRINCIPAL, 01.01.1980 года рождения, ИИН 000000000001, проживающий по адресу TEST, настоящей доверенностью уполномочиваю гр. TEST APPROVED PERSON, 01.01.1980 года рождения, ИИН 000000000002, на следующее: представлять мои интересы. Доверенность выдана сроком до test expiry.';
test('principal is not confused with representative or notary identifiers',()=>{const r=extractPowerParties(power);assert.equal(r.principal.iin,'000000000001');assert.equal(r.representative.identifier,'000000000002');assert.equal(r.expiresText,'до test expiry');assert.equal(checkPowerRepresentative(r).representativeMatched,true);assert.equal(checkPowerRepresentative(r).authorityVerified,false);});
test('organization representative requires its BIN and exact authorized legal name',()=>{const r=extractPowerParties(power.replace('гр. TEST APPROVED PERSON, 01.01.1980 года рождения, ИИН 000000000002','ТОО «TEST ORGANIZATION», БИН 000000000003'));assert.equal(r.representative.kind,'organization');assert.equal(checkPowerRepresentative(r).representativeMatched,true);r.representative.legalName='ТОО «OTHER»';assert.equal(checkPowerRepresentative(r).representativeMatched,false);});
test('additional representative identifiers remain ambiguous',()=>{const r=extractPowerParties(power.replace('на следующее:','и гр. OTHER, ИИН 000000000004, на следующее:'));assert.equal(r.representative,null);assert.ok(r.findings.includes('REPRESENTATIVE_IDENTITY_UNVERIFIED'));});
test('a document mentioning a power without the principal/delegation clause cannot supply parties',()=>{const r=extractPowerParties('Договор. Предоставить доверенность. ИИН 000000000002.');assert.equal(r.principal,null);assert.equal(r.representative,null);});
