import {test} from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import ts from 'typescript';import {webcrypto} from 'node:crypto';
const exports={};const src=fs.readFileSync(new URL('../lib/worker-session.ts',import.meta.url),'utf8');vm.runInNewContext(ts.transpileModule(src,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,crypto:webcrypto,TextEncoder,TextDecoder,Uint8Array,btoa,atob,Request,URL,Date});const m=exports;
const secret='unit-test-only-session-key-not-used-in-runtime';
test('same four worker choices; unknown/prototype names cannot authenticate',()=>{for(const id of ['ali','ramazan','nurdaulet','darkhan'])assert.equal(m.authenticateWorker(id,'test-only','test-only').id,'worker:'+id);for(const id of ['toString','constructor','unknown'])assert.equal(m.authenticateWorker(id,'test-only','test-only'),null);assert.equal(m.authenticateWorker('ali','wrong','test-only'),null)});
test('valid signed session preserves a portable actor',async()=>{const t=await m.issueSession('ramazan',secret,1000);const a=await m.verifySession(t,secret,1001);assert.equal(a.id,'worker:ramazan');assert.equal(a.authentication,'shared-password-worker-selection');});
test('changing actor inside token invalidates signature',async()=>{const t=await m.issueSession('ramazan',secret,1000);const [p,s]=t.split('.');const body=JSON.parse(Buffer.from(p,'base64url'));body.sub='ali';const changed=Buffer.from(JSON.stringify(body)).toString('base64url')+'.'+s;assert.equal(await m.verifySession(changed,secret,1001),null)});
test('expired, cross-key, future and malformed sessions rejected',async()=>{const t=await m.issueSession('ali',secret,1000);assert.equal(await m.verifySession(t,secret,1000+m.SESSION_SECONDS),null);assert.equal(await m.verifySession(t,secret+'other',1001),null);assert.equal(await m.verifySession(t,secret,0),null);assert.equal(await m.verifySession('ali.legacy-token',secret),null);});
test('duplicate cookies are ambiguous and rejected',()=>{const c=m.SESSION_COOKIE;assert.equal(m.readSessionCookie(`${c}=a; ${c}=b`),null);assert.equal(m.readSessionCookie(`${c}=value`),'value')});
test('foreign-origin writes rejected',()=>{assert.equal(m.requestOriginAllowed(new Request('https://site.test/api/session',{method:'POST',headers:{origin:'https://evil.test'}})),false);assert.equal(m.requestOriginAllowed(new Request('https://site.test/api/session',{method:'POST',headers:{origin:'https://site.test'}})),true)});
